### ISSUE TITLE
parameters.jl in Getting Started

### ISSUE THREAD

**Issue by smjanke** [NQCD/NonadiabaticMolecularDynamics.jl#103]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/3132608e9ee40331f6e72ea578abc4ef8887cd0e/docs/src/getting_started.md#L55

Cool box!
What are 'keyword constructors' and what is 'nice printing'? (i.e., is nice printing just formating or is it some kind of explanation?
Perhaps write what keyword constructors do and than put (keyword constructors) behind that. For nice printing, is there a way to describe more clearly what that means?

**Comment by jamesgardner1421** [comment]
Yeah maybe it would be good to elaborate some more. By "keyword constructor" I just mean a function that constructs the type where each argument is a keyword argument. I think it's not unreasonable to expect the reader to know what a constructor is but there's no harm in being more explicit.

For "nice printing" I just meant that it formatted the parameters nicely when printing the type. But yeah let's make this box more descriptive.
