### ISSUE TITLE
Getting started, Model

### ISSUE THREAD

**Issue by smjanke** [NQCD/NonadiabaticMolecularDynamics.jl#104]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/6039a6c2e0c9be83868f8f0fc9a04d6fd7e978f6/docs/src/getting_started.md#L66

The hcat box is really useful!
Before explaining about hcat, please explain how to set up R in general, so by an example for a 1D and 3D case. At the moment, I would not know how to define positions for my system. Could also be a link to another page.

**Comment by jamesgardner1421** [comment]
This is a good point, I think before introducing the models there should be another subsection (maybe "Positions") which describes that we represent positions using ndofs*natoms matrices.

**Comment by smjanke** [comment]
That's a great idea!
