### ISSUE TITLE
Getting started: Running ensembles

### ISSUE THREAD

**Issue by smjanke** [NQCD/NonadiabaticMolecularDynamics.jl#108]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/6039a6c2e0c9be83868f8f0fc9a04d6fd7e978f6/docs/src/getting_started.md#L180

This section needs examples.

**Comment by jamesgardner1421** [comment]
Oh yeah this is kind of weird. Looks like I forgot to finish this. I think it might be best to link to the ensembles page here rather than bloating the getting started section too much.

**Comment by smjanke** [comment]
Yes, that is a good idea I think.
