### ISSUE TITLE
Semiclassical EBK

### ISSUE THREAD

**Issue by smjanke** [NQCD/NonadiabaticMolecularDynamics.jl#131]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/b34044976cc936bc89c0b59a073316a706e50872/docs/src/initialconditions/samplingmethods/ebk.md#L3

What is the purpose of this page? Is it still a stubb?

**Comment by jamesgardner1421** [comment]
I didn't finish this page off, I wanted to get Oscar to put some of his work here and possibly some of the plots from the paper that he made for the SI.
